### PR TITLE
[BOOM] Rebase with upstream master

### PR DESCRIPTION
**Pull request by BarthV**
### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by vdemonchy** [comment]
+1! Should be not risky for now as we currently use the memcached-ng branch.

**Comment by kamaradclimber** [comment]
Any reason to do that considering that memcached-ng branch that is used by your team hasbeen merged in master branch ?

I think you should close that fork.

**Comment by BarthV** [comment]
We need to modify it afterwards (just for some time) so we just need to keep this fork ATM.
We'll remove it after all this operations.

**Comment by mcoolive** [comment]
I rebase the master branch. It is unused curently. We keep it for the moment because we have few changes not included on the original repository.
TO DO:
1. list changes in ng-memcached not merged on the original repository
2. re-apply them (if needed) on master
3. close ng-memcached branch
4. Open PR on the original repository

**Pull request merged**
